sudo: required
dist: presice
language: cpp

matrix:
    include:
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-4.9
          env: COMPILER=g++-4.9
        - compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-5.0
          env: COMPILER=g++-5.0
        - compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.6
                  packages:
                      - clang-3.6
          env: COMPILER=clang++-3.6
        - compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-precise-3.6
                  packages:
                      - clang-3.7
          env: COMPILER=clang++-3.7

#addons:
#    apt:
#        packages:
#            - cmake
#            - ctest
before_script:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-all-dev
    - curl -O https://cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
    - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
    - sudo cp -fR cmake-3.2.3-Linux-x86_64/* /usr
script:
    - mkdir build
    - cd build
    - cmake -DMAKE_CXX_COMPILER=$COMPILER .. && make && ctest
